import java.util.Scanner;


public class RomanoANumero {
 static int conversor(String variablea){
	 int num = 0;
	 switch(variablea){
	 case "I": num=1;
	          break; 
	 case "II": num=2;
     break; 
	 case "III": num=3;
     break; 
	 case "IV": num=4;
     break; 
	 case "V": num=5;
     break; 
	 case "VI": num=6;
     break; 
	 case "VII": num=7;
     break; 
	 case "VIII": num=8;
     break; 
	 case "IX": num=9;
     break; 
	 case "X": num=10;
     break; 
	 case "XI": num=11;
     break; 
	 case "XII": num=12;
     break; 
	 case "XIII": num=13;
     break; 
	 case "XIV": num=14;
     break; 
	 case "XV": num=15;
     break; 
	 case "XVI": num=16;
     break; 
	 case "XVII": num=17;
     break; 
	 case "XVIII": num=18;
     break; 
	 case "XIX": num=19;
     break; 
	 case "XX": num=20;
     break; 
	 case "XXI": num=21;
     break; 
	 case "XXII": num=22;
     break; 
	 case "XXIII": num=23;
     break; 
	 case "XXIV": num=24;
     break; 
	 case "XXV": num=25;
     break; 
	 case "XXVI": num=26;
     break; 
	 case "XXVII": num=27;
     break; 
	 case "XXVIII": num=28;
     break; 
	 case "XXIX": num=29;
     break; 
	 case "XXX": num=30;
     break; 
	 case "XXXI": num=31;
     break; 
	 case "XXXII": num=32;
     break; 
	 case "XXXIII": num=33;
     break; 
	 case "XXXIV": num=34;
     break; 
	 case "XXXV": num=35;
     break; 
	 case "XXXVI": num=36;
     break; 
	 case "XXXVII": num=37;
     break; 
	 case "XXXVIII": num=38;
     break; 
	 case "XXXIX": num=39;
     break; 
	 case "XL": num=40;
     break; 
	 case "XLI": num=41;
     break; 
	 case "XLII": num=42;
     break;
	 case "XLIII": num=43;
     break;
	 case "XLIV": num=44;
     break;
	 case "XLV": num=45;
     break;
	 case "XLVI": num=46;
     break;
	 case "XLVII": num=47;
     break;
	 case "XLVIII": num=48;
     break;
	 case "XLIX": num=49;
     break;
	 case "L": num=50;
     break;
	 case "LI": num=51;
     break;
	 case "LII": num=52;
     break;
	 case "LIII": num=53;
     break;
	 case "LIV": num=54;
     break;
	 case "LV": num=55;
     break;
	 case "LVI": num=56;
     break;
	 case "LVII": num=57;
     break;
	 case "LVIII": num=58;
     break;
	 case "LIX": num=59;
     break;
	 case "LX": num=60;
     break;
	 case "LXI": num=61;
     break;
	 case "LXII": num=62;
     break;
	 case "LXIII": num=63;
     break;
	 case "LXIV": num=64;
     break;
	 case "LXV": num=65;
     break;
	 case "LXVI": num=66;
     break;
	 case "LXVII": num=67;
     break;
	 case "LXVIII": num=68;
     break;
	 case "LXIX": num=69;
     break;
	 case "LXX": num=70;
     break;
	 case "LXXI": num=71;
     break;
	 case "LXXII": num=72;
     break;
	 case "LXXIII": num=73;
     break;
	 case "LXXIV": num=74;
     break;
	 case "LXXV": num=75;
     break;
	 case "LXXVI": num=76;
     break;
	 case "LXXVII": num=77;
     break;
	 case "LXXVIII": num=78;
     break;
	 case "LXXIX": num=79;
     break;
	 case "LXXX": num=80;
     break;
	 case "LXXXI": num=81;
     break;
	 case "LXXXII": num=82;
     break;
	 case "LXXXIII": num=83;
     break;
	 case "LXXXIV": num=84;
     break;
	 case "LXXXV": num=85;
     break;
	 case "LXXXVI": num=86;
     break;
	 case "LXXXVII": num=87;
     break;
	 case "LXXXVIII": num=88;
     break;
	 case "LXXXIX": num=89;
     break;
	 case "XC": num=90;
     break;
	 case "XCI": num=91;
     break;
	 case "XCII": num=92;
     break;
	 case "XCIII": num=93;
     break;
	 case "XCIV" : num=94;
     break;
	 case "XCV": num=95;
     break;
	 case "XCVI": num=96;
     break;
	 case "XCVII": num=97;
     break;
	 case "XCVIII": num=98;
     break;
	 case "XCIX": num=99;
     break;
     }
	return num;
	
	
	 
		
 }
}
